### ISSUE TITLE
[New feature] Download data in CSV

### ISSUE THREAD

**Issue by kisvegabor** [repotraffic/repotraffic-feedback#5]
Hi,

First of all, thank you for this great tool! I use it a lot!

I have an idea about a small feature:
It seems useful to be able to download the data in CSV (or similar format) to do some statistics on it.
What do think? Would it be a possible update in the future?

Thank you in advance!

**Comment by burnash** [comment]
Thank you for the feedback and for kind words! I'm sorry for the late reply. Looks like this feature in high demand (#1). I think it's a possible update in the future: I'm considering opensoucing the project (#6).
