### ISSUE TITLE
Question: Repo limit & further plans

### ISSUE THREAD

**Issue by petrsvihlik** [repotraffic/repotraffic-feedback#7]
Hi, thanks for this nice project!

[This article](http://www.ilovefreesoftware.com/17/tutorial/track-traffic-github-repos-longer-than-14-days.html) mentions a repo limit of 5 repos. 

Is there any plan on removing that restriction? 
Is there a plan on extending the capabilities? It would be great if the app covered the whole github traffic api (clones, referrers, popular content)?
Is there any plan on measuring the data on the user/organization level? (Aggregate report for multiple repos)

**Comment by burnash** [comment]
Thanks for your feedback and for the ideas.

> This article mentions a repo limit of 5 repos.
> Is there any plan on removing that restriction?

Could you please elaborate on why do you actually need it? Repotraffic is almost two years old. I put this note in the app settings when I launched the app:

> "Select repos to store traffic data. Maximum 5. Drop me a line if you need more." 

In two years I received only one message with a request to raise this limit. Currently the service is tracking 10k+ repos.

> Is there a plan on extending the capabilities? It would be great if the app covered the whole github traffic api (clones, referrers, popular content)?

I've created the app to track my own open souce project: [gspread](https://github.com/burnash/gspread). So far I didn't need historical data for clones (or maybe I didn't see the value behind this type of data). Same for referrers and popular content. If the project eventually gets open sourced (#6) I think this will be one of the first features. It's already in the issues: #3 

> Is there any plan on measuring the data on the user/organization level? (Aggregate report for multiple repos)

Good idea. Personally I don't need it. It would be great to see if there's demand for such a feature. Coud you create a feature request for it?

**Comment by petrsvihlik** [comment]
We were looking for a solution that would allow us to track GitHub stats across our [organization](https://github.com/Kentico/). Currently, we use a workaround called Google Analytics Beacon for keeping track of page views. We ported https://github.com/igrigorik/ga-beacon to .NET (https://github.com/Kentico/google-analytics-beacon-net).
Hope this clarifies our motivation and answers your questions.
