### ISSUE TITLE
why does repotraffic need write access to my repo?

### ISSUE THREAD

**Issue by dan-da** [repotraffic/repotraffic-feedback#8]
I went to try repotraffic, but I saw that repotraffic wants write access.   Why is that so?

Here's the message:

```
This application will be able to read and write all public repository data. This includes the following:

    Code
    Issues
    Pull requests
    Wikis
    Settings
    Webhooks and services
    Deploy keys
```

**Comment by burnash** [comment]
Thank you for your feedback. Please see the detailed response here: https://github.com/repotraffic/repotraffic-feedback/issues/6#issuecomment-432638356
